// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNEPDGEx_iTA0DKqxkyQUdBNnfn8Bxx3g',
    appId: '1:421669563863:web:485746127f2326b699af92',
    messagingSenderId: '421669563863',
    projectId: 'khidmat-project',
    authDomain: 'khidmat-project.firebaseapp.com',
    storageBucket: 'khidmat-project.firebasestorage.app',
    measurementId: 'G-8B4CVTHKQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD21fu1wWBdZzknkzqJCd1_YaEUbXbsU4k',
    appId: '1:421669563863:android:b76b2b451cbcb0dc99af92',
    messagingSenderId: '421669563863',
    projectId: 'khidmat-project',
    storageBucket: 'khidmat-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgeVxNynH64AVUo3OFJbXacaq7pDVWM1E',
    appId: '1:421669563863:ios:2917d8e1821be7fd99af92',
    messagingSenderId: '421669563863',
    projectId: 'khidmat-project',
    storageBucket: 'khidmat-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgeVxNynH64AVUo3OFJbXacaq7pDVWM1E',
    appId: '1:421669563863:ios:2917d8e1821be7fd99af92',
    messagingSenderId: '421669563863',
    projectId: 'khidmat-project',
    storageBucket: 'khidmat-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNEPDGEx_iTA0DKqxkyQUdBNnfn8Bxx3g',
    appId: '1:421669563863:web:a6f9ee08f7f99b4a99af92',
    messagingSenderId: '421669563863',
    projectId: 'khidmat-project',
    authDomain: 'khidmat-project.firebaseapp.com',
    storageBucket: 'khidmat-project.firebasestorage.app',
    measurementId: 'G-CND5SM055Q',
  );

}